### PR TITLE
feat: added dartServices.analyze(source)

### PR DESCRIPTION
**Pull request by tomoyuki28jp**

### CODE REVIEW

**Comment by softmarshmallow** [comment]
Thank you :)
Embarrassed that i missed this.

P.s. this service will be migrated under https://github.com/gridaco/flutter repo soon.

**Comment by tomoyuki28jp** [comment]
@softmarshmallow Thank you for your quick response!

Could you release a new version? 

`yarn add 'https://gitpkg.now.sh/gridaco/base/packages/dartservices?main'` and `import DartServices from "dart-services";` raises `Cannot find module 'dart-services' or its corresponding type declarations.` error somehow.

**Comment by softmarshmallow** [comment]
Sure, after moving to gridaco/flutter repo, I'll take a look into that error and make a new npm release, I'll mention you in a new PR.

**Comment by softmarshmallow** [comment]
Can you try with new version just released?

https://github.com/gridaco/flutter/pull/17

**Pull request merged**
